version: '3.9'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  books-catalogue:
    build:
      context: ./ms-books-catalogue
    container_name: ms-books-catalogue
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - backend

networks:
  backend:
    driver: bridge