spring:
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue
